### ISSUE TITLE
Casi...

### ISSUE THREAD

**Issue by NITDev94** [4GeeksAcademy/GusCastle25-Instagram-Feed-con-Bootstrap#2]
Te han faltado al menos 3 cosas:

1. Los botones de create new post y settings están pegados y no debería.
2. Ninguna de las filas tiene el mismo height, averigua porque (hay varias razones, no todas las filas las tienes igual).
3. En el collage tambien, toca el bottom y debería de haber aire entre la ultima fila y el final de la web, porque parece que se solapan e incluso se pierde un poco de foto. En los posts tambien el primero toca el nav pills y no debería, lo mismo con el collage la primera linea toca el nav pils, dale aire arriba y abajo.

**Comment by GusCastle25** [comment]
Listo, creo que he modificado y entendido todo lo que me pedistes. Si vez que no he entendido o no ha quedado como me pedias, por favor avísame para pedir una mentoría y comprender mejor tus observaciones. Gracias!!!
